# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    dotnet build src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj --configuration Release
  displayName: "Build"

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    configuration: 'Release'
  displayName: "Nuget Pack"

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: nuget.org
  displayName: "Nuget Authenticate"

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: nuget.org
  displayName: "Nuget Push"
