# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    dotnet build src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj --configuration Release
  displayName: "Build"

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    configuration: 'Release'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: nuget-pasmonteiro

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    versioningScheme: byBuildNumber
