name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj -c Release --no-restore
    - name: Nuget Pack
      run: dotnet pack src/Grpc.Testing.Moq/Grpc.Testing.Moq.csproj -p:PackageVersion=1.0.0 -c Release
    - name: Nuget Push
      run: nuget push ./**/*.nupkg --source ${{ vars.NUGETSOURCE }} --api-key ${{ secrets.NUGETTOKEN }} --skip-duplicate --no-symbols true
